### ISSUE TITLE
Potential area for optimization

### ISSUE THREAD

**Issue by Nedwardo** [petersn/web-sploosh-kaboom#34]
I don't know how relevant this or, how true this is.
But would it not be more optimial to instead of firing where there is a highest probability of success i.e. to hit a ship. To fire where there is the ability to spilt the state space in half. I.e. the area cloest to 50%, like in guess who?

**Comment by petersn** [comment]
Hey, sorry, this deserves a longer write up. We've explored various heuristics, and trying to shoot at the cell that's closest to 50% (or other heuristics) actually does reduce the expected number of shots by some very small amount, but it dramatically increases the average amount of cursor motion compared to just shooting at the most likely spot. (If you shoot at the most likely spot then it's encouraged to try to complete squids it's pretty confident in.)

In fact, because of the locality thing we don't even shoot at the most likely spot, we currently shoot at the most likely spot minus a slight penalty for L1 distance, so it'll suggest a 90% cell that's right next to your cursor instead of a 100% cell on the other side of the board.

I'm definitely open to changes in the selection algorithm, but I suspect that there are more wins to be had fixing the locality issues. It still sometimes asks you to do dumb things like go back and forth between two squids it's exploring.

**Comment by Nedwardo** [comment]
Sorry for being one of many for the same suggestion, but glad to see the issue is well understood.
